import React from 'react';
import Button from './Button.jsx';

export default function Layout({ children }) {
  return (
    <div className='min-h-screen flex flex-col bg-slate-900 text-slate-50'>
      <header className='border-b border-slate-800 px-6 py-4 flex items-center justify-between'>
        <h1 className='text-xl font-semibold'>Origo Starter</h1>
        <Button>Primary Action</Button>
      </header>
      <main className='flex-1 px-6 py-8'>{children}</main>
      <footer className='border-t border-slate-800 px-6 py-4 text-sm text-slate-400'>
        Generated by Origo fallback template.
      </footer>
    </div>
  );
}
