from typing import Any, Dict


def build_minimal_fullstack_fallback() -> Dict[str, Any]:
    """Return a fully functional React+Tailwind + FastAPI template.

    This is used when the LLM output is invalid or incomplete, so it must
    satisfy validation.REQUIRED_FRONTEND_FILES and REQUIRED_BACKEND_FILES.
    """

    frontend_files = {
        "public/index.html": (
            "<!doctype html>\n"
            "<html lang='en'>\n"
            "  <head>\n"
            "    <meta charset='utf-8' />\n"
            "    <title>Origo App</title>\n"
            "  </head>\n"
            "  <body class='bg-gray-50'>\n"
            "    <div id='root'></div>\n"
            "    <script type='module' src='/src/index.js'></script>\n"
            "  </body>\n"
            "</html>\n"
        ),
        "src/index.js": (
            "import React from 'react';\n"
            "import { createRoot } from 'react-dom/client';\n"
            "import App from './App.jsx';\n"
            "import './index.css';\n\n"
            "const container = document.getElementById('root');\n"
            "const root = createRoot(container);\n"
            "root.render(<App />);\n"
        ),
        "src/App.jsx": (
            "import React from 'react';\n"
            "import Layout from './components/Layout.jsx';\n"
            "import Home from './pages/Home.jsx';\n\n"
            "export default function App() {\n"
            "  return (\n"
            "    <Layout>\n"
            "      <Home />\n"
            "    </Layout>\n"
            "  );\n"
            "}\n"
        ),
        "src/components/Layout.jsx": (
            "import React from 'react';\n"  
            "import Button from './Button.jsx';\n\n"
            "export default function Layout({ children }) {\n"
            "  return (\n"
            "    <div className='min-h-screen flex flex-col bg-slate-900 text-slate-50'>\n"
            "      <header className='border-b border-slate-800 px-6 py-4 flex items-center justify-between'>\n"
            "        <h1 className='text-xl font-semibold'>Origo Starter</h1>\n"
            "        <Button>Primary Action</Button>\n"
            "      </header>\n"
            "      <main className='flex-1 px-6 py-8'>{children}</main>\n"
            "      <footer className='border-t border-slate-800 px-6 py-4 text-sm text-slate-400'>\n"
            "        Generated by Origo fallback template.\n"
            "      </footer>\n"
            "    </div>\n"
            "  );\n"
            "}\n"
        ),
        "src/components/Button.jsx": (
            "import React from 'react';\n\n"
            "export default function Button({ children, ...props }) {\n"
            "  return (\n"
            "    <button\n"
            "      className='inline-flex items-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white shadow-sm hover:bg-indigo-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2'\n"
            "      {...props}\n"
            "    >\n"
            "      {children}\n"
            "    </button>\n"
            "  );\n"
            "}\n"
        ),
        "src/pages/Home.jsx": (
            "import React from 'react';\n"
            "import useApi from '../hooks/useApi.js';\n\n"
            "export default function Home() {\n"
            "  const { data, loading, error } = useApi('/health');\n\n"
            "  return (\n"
            "    <div className='max-w-2xl space-y-4'>\n"
            "      <h2 className='text-2xl font-semibold tracking-tight'>Welcome to your Origo app</h2>\n"
            "      <p className='text-slate-300'>This is a minimal fullstack starter wired to a FastAPI backend.</p>\n"
            "      <div className='rounded-md border border-slate-800 bg-slate-900/60 p-4 text-sm font-mono'>\n"
            "        <div className='mb-1 text-slate-400'>Backend health:</div>\n"
            "        {loading && <div>Loading...</div>}\n"
            "        {error && <div className='text-red-400'>Error: {error}</div>}\n"
            "        {data && <pre>{JSON.stringify(data, null, 2)}</pre>}\n"
            "      </div>\n"
            "    </div>\n"
            "  );\n"
            "}\n"
        ),
        "src/hooks/useApi.js": (
            "import { useEffect, useState } from 'react';\n\n"
            "export default function useApi(path) {\n"
            "  const [data, setData] = useState(null);\n"
            "  const [loading, setLoading] = useState(true);\n"
            "  const [error, setError] = useState(null);\n\n"
            "  useEffect(() => {\n"
            "    async function run() {\n"
            "      try {\n"
            "        const res = await fetch(`http://localhost:8000${path}`);\n"
            "        if (!res.ok) throw new Error(res.statusText);\n"
            "        const json = await res.json();\n"
            "        setData(json);\n"
            "      } catch (err) {\n"
            "        setError(err.message || 'request-failed');\n"
            "      } finally {\n"
            "        setLoading(false);\n"
            "      }\n"
            "    }\n"
            "    run();\n"
            "  }, [path]);\n\n"
            "  return { data, loading, error };\n"
            "}\n"
        ),
        "src/services/api.js": (
            "export async function getJson(path) {\n"
            "  const res = await fetch(`http://localhost:8000${path}`);\n"
            "  if (!res.ok) {\n"
            "    throw new Error(res.statusText);\n"
            "  }\n"
            "  return res.json();\n"
            "}\n"
        ),
        "src/index.css": (
            "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n"
        ),
        "tailwind.config.js": (
            "module.exports = {\n"
            "  content: ['./public/index.html', './src/**/*.{js,jsx,ts,tsx}'],\n"
            "  theme: { extend: {} },\n"
            "  plugins: [],\n"
            "};\n"
        ),
        "postcss.config.js": (
            "module.exports = {\n"
            "  plugins: {\n"
            "    tailwindcss: {},\n"
            "    autoprefixer: {},\n"
            "  },\n"
            "};\n"
        ),
    }

    backend_files = {
        "app/main.py": (
            "from fastapi import FastAPI\n"
            "from fastapi.middleware.cors import CORSMiddleware\n"
            "from app.routes import api as api_router\n\n"
            "app = FastAPI(title='origo-fallback-backend')\n\n"
            "app.add_middleware(\n"
            "    CORSMiddleware,\n"
            "    allow_origins=['*'],\n"
            "    allow_methods=['*'],\n"
            "    allow_headers=['*'],\n"
            ")\n\n"
            "@app.get('/health')\n"
            "def health():\n"
            "    return {'status': 'ok'}\n\n"
            "app.include_router(api_router.router, prefix='/api')\n"
        ),
        "app/routes/__init__.py": "# routes package for Origo fallback backend\n",
        "app/routes/api.py": (
            "from fastapi import APIRouter\n\n"
            "router = APIRouter()\n\n"
            "@router.get('/projects')\n"
            "def list_projects():\n"
            "    return {'projects': []}\n"
        ),
        "app/schemas/__init__.py": "# schemas package for Origo fallback backend\n",
        "app/models/__init__.py": "# models package for Origo fallback backend\n",
        "app/services/__init__.py": "# services package for Origo fallback backend\n",
    }

    readme = (
        "# Origo Fullstack Fallback Project\n\n"
        "This project was generated using Origo's fallback defaults because the LLM output was incomplete.\n\n"
        "## Frontend (React + Tailwind)\n"
        "- npm install\n"
        "- npm start\n\n"
        "## Backend (FastAPI)\n"
        "- pip install fastapi uvicorn\n"
        "- uvicorn app.main:app --reload\n"
    )

    return {
        "frontend_files": frontend_files,
        "backend_files": backend_files,
        "README": readme,
    }
