from __future__ import annotations

from typing import Any, Dict

from app.services.validation import REQUIRED_FRONTEND_FILES, REQUIRED_BACKEND_FILES


def fill_missing_files(output: Dict[str, Any]) -> Dict[str, Any]:
    """Second pass that ensures required files exist.

    If the LLM omitted some required files but others are present, we create
    minimal placeholder implementations so that validation will pass and
    the project structure is complete.
    """
    if not isinstance(output, dict):
        return output

    frontend = output.get("frontend_files") or {}
    backend = output.get("backend_files") or {}

    if not isinstance(frontend, dict):
        frontend = {}
    if not isinstance(backend, dict):
        backend = {}

    # Fill required frontend files
    if "src/App.jsx" not in frontend:
        frontend["src/App.jsx"] = (
            "import React from 'react';\n\n"
            "export default function App(){\n"
            "  return <div className='p-6'>Origo App</div>;\n"
            "}\n"
        )
    if "src/index.js" not in frontend:
        frontend["src/index.js"] = (
            "import React from 'react';\n"
            "import { createRoot } from 'react-dom/client';\n"
            "import App from './App.jsx';\n\n"
            "const root = createRoot(document.getElementById('root'));\n"
            "root.render(<App />);\n"
        )
    if "public/index.html" not in frontend:
        frontend["public/index.html"] = (
            "<!doctype html><html><head><meta charset='utf-8'><title>Origo</title></head>"
            "<body><div id='root'></div><script src='/src/index.js'></script></body></html>"
        )

    # Fill required backend files
    if "app/main.py" not in backend:
        backend["app/main.py"] = (
            "from fastapi import FastAPI\n\n"
            "app = FastAPI(title='origo-backend')\n\n"
            "@app.get('/health')\n"
            "def health():\n"
            "    return {'status': 'ok'}\n"
        )
    if "app/routes/__init__.py" not in backend:
        backend["app/routes/__init__.py"] = "# routes package\n"
    if "app/routes/api.py" not in backend:
        backend["app/routes/api.py"] = (
            "from fastapi import APIRouter\n\n"
            "router = APIRouter()\n\n"
            "@router.get('/projects')\n"
            "def list_projects():\n"
            "    return {'projects': []}\n"
        )
    if "app/schemas/__init__.py" not in backend:
        backend["app/schemas/__init__.py"] = "# schemas package\n"
    if "app/models/__init__.py" not in backend:
        backend["app/models/__init__.py"] = "# models package\n"
    if "app/services/__init__.py" not in backend:
        backend["app/services/__init__.py"] = "# services package\n"

    output["frontend_files"] = frontend
    output["backend_files"] = backend
    if not isinstance(output.get("README"), str) or not output["README"].strip():
        output["README"] = "# Origo Project\n\nGenerated by Origo."

    return output
